//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int idUser { get; set; }
        public string login1 { get; set; }
        public int password { get; set; }
        public int idRole { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
